Mlir improvements
Shuriken-Group/Shuriken-Analyzer pull request #97
Opened 2024-11-23 18:14 UTC by badumbatish

2024-11-29 14:39 UTC, jeppojeps reviewed
it looks good to me

2024-11-29 14:39 UTC, jeppojeps commented on shuriken/mjolnir/lib/transform/lifter.cpp
> +    context.loadAllAvailableDialects();
do we really need all available dialects? Wouldn't it be an overkill?

2024-12-04 11:41 UTC, Fare9 approved these changes

2024-12-04 12:34 UTC, Fare9 reviewed
Check in runtime if the instructions are generated correctly, you can use `_int.dex` to test if the arithmetic instructions are generated.

2024-12-04 12:37 UTC, Fare9 requested changes
Try `shuriken-opt` and check that the output generates the correct instructions.

2024-12-04 15:00 UTC, Fare9 approved these changes

2024-12-04 15:00 UTC, merged